sylius_customer:
    resources:
        customer:
                classes:
                    model: AppBundle\Entity\Customer

sylius_order:
    resources:
        order:
            classes:
                controller: AppBundle\Controller\OrderController
